const menu_item = [
    {
        id: 1,
        type: 'drink',
        name: 'TTra sua chan trau',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 2,
        type: 'drink',
        name: 'Kem Osc qua',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
    {
        id: 3,
        type: 'drink',
        name: 'Tra hoa qua',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 4,
        type: 'drink',
        name: 'Banh My pate',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 5,
        type: 'food',
        name: 'Tra Sua chana dhas',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
    {
        id: 4,
        type: 'drink',
        name: 'Banh My pate',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 5,
        type: 'food',
        name: 'Tra Sua chana dhas',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
    {
        id: 6,
        type: 'drink',
        name: 'Banh My pate',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 7,
        type: 'food',
        name: 'Tra Sua chana dhas',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
    {
        id: 8,
        type: 'drink',
        name: 'BMy Quang',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 9,
        type: 'food',
        name: 'Tra Sua chana dhas',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
    {
        id: 10,
        type: 'drink',
        name: 'Banh My pate',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 11,
        type: 'food',
        name: 'Tra Sua chana dhas',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: true,
    },
    {
        id: 12,
        type: 'drink',
        name: 'Banh My pate',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
    {
        id: 13,
        type: 'food',
        name: 'Sua Chua',
        detail: 'Nuwosc uosng',
        price: '20000',
        quantity: 20,
        sale: true,
        favorite: false,
    },
];

module.exports = menu_item;
